#ifndef DEKLARACJE_H_INCLUDED
#define DEKLARACJE_H_INCLUDED

#define maxstring 8
#define spiecesNumber 7
enum ZWIERZETA { KON, OSIOL, MUL, JASTRZAB, MYSZOLOW, MYSZ, ZAJAC };

#endif // DEKLARACJE_H_INCLUDED
